### ISSUE TITLE
Rules don't work when adding a new permission

### ISSUE THREAD

**Issue by Rover350z** [yajra/laravel-admin-template#3]
I have added a new permission through the database. I can assign the permission to a role, and had added the route in `app/routes.php` and Entrust filter to `app/filters.php`. However, when I try to reach the route via the assigned role, i get redirected to the dashboard.

Is this a bug? Or did i just miss something?

**Comment by yajra** [comment]
Most probably you missed something on your setup. Also note that you must have at least `admin` role to access the admin site.

```php
// Check for role on all admin routes, minimum admin level
Entrust::routeNeedsRole( 'admin*', array('admin'), Redirect::to('/') );
```

**Comment by Rover350z** [comment]
Well.. This must be right then.

`app/filters.php`

    // Check for role on all admin routes, minimum admin level
    Entrust::routeNeedsRole( 'admin*', array('admin'), Redirect::to('/') );
    
    // Check for permissions on admin actions
    Entrust::routeNeedsPermission( 'admin/blogs*', 'manage_blogs', Redirect::to('/admin') );
    Entrust::routeNeedsPermission( 'admin/galleries*', 'manage_galleries', Redirect::to('/admin') );
    Entrust::routeNeedsPermission( 'admin/comments*', 'manage_comments', Redirect::to('/admin') );
    Entrust::routeNeedsPermission( 'admin/users*', 'manage_users', Redirect::to('/admin') );
    Entrust::routeNeedsPermission( 'admin/roles*', 'manage_roles', Redirect::to('/admin') );

If i comment this Entrust filter everything works, except the role does'nt work obviously.

The permission is available in the admin panel, and also linked to the admin account. 

`app/routes.php`
`Route::model('gallery', 'Gallery');`
`Route::controller('galleries', 'AdminGalleriesController');`

**Comment by yajra** [comment]
I think you're trying to limit the access on galleries part right?
If that is the case then consider this example:
```
admin user
  -> admin Role
     -> manage_blogs
     -> manage_galleries
     -> ....

user
  -> user Role
     -> manage_galleries
```

admin should be able to access the galleries as he has `manage_galleries` permission and has `admin` role.

However, user don't have access on it although he does have `manage_galleries` permission because he doesnt have `admin` role. 
For user to have access, you must add a `admin` role to him.

```
user
  -> admin role
     -> @inherit
  -> user Role
     -> manage_galleries
```

Does your setup somewhat like this?


Another way is change the minimum role to `user` or something that every user must have. Then create another role that you can attach to the user to add addition permissions.

**Comment by Rover350z** [comment]
Ah this is stupid, the database field was called `manage_gallleries`. Three l's, yeah. Hard to notice. Im going to close this now.
